mahasewa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import pages.urls as index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(('pages.urls', 'pages'), namespace='pages')),
]

pages/urls.py
from django.conf.urls import url
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^about/', about, name='about'),
    url(r'^katalog/', katalog, name='katalog'),
    url(r'^apartment/(?P<aptId>[0-9]+)',apartment, name='apartment'),
    url(r'^room/(?P<roomId>[0-9]+)',room, name='room'),
    path('blog/', blog, name='blog')

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/models.py
from django.db import models

# Create your models here.
class Apartment(models.Model):
	name = models.CharField(max_length=20, blank=False)
	address = models.TextField(blank=False)
	descTextbox = models.TextField(blank=False,verbose_name='Description')
	image = models.ImageField(upload_to = "static/images/apartment", default=" " )
	location = models.CharField(max_length=50, blank=False, default="not set")
	def __str__(self):
		return self.name

class Room(models.Model):
	no = models.CharField(max_length=20, blank=False)
	apartment = models.ForeignKey(Apartment, on_delete=models.CASCADE)
	tower     = models.CharField(max_length=1)
	floor = models.CharField(max_length=20, blank=False)
	descTextbox = models.TextField(blank=False,verbose_name='Description')
	pricePlaceholder = models.CharField(max_length=20, blank=False,verbose_name='Price')

	def __str__(self):
		return self.no

class RoomImage(models.Model):
	room = models.ForeignKey(Room, related_name='images', on_delete=models.CASCADE)
	image = models.ImageField(upload_to = "static/images/room" )

class AptFacility(models.Model):
	apartment = models.ForeignKey(Apartment, related_name='facility', on_delete=models.CASCADE)
	facilityTextbox = models.CharField(max_length=20, blank=False,verbose_name='Facility')
	image = models.ImageField(upload_to = "static/images/facilityLogo", default= "null")

class RoomFacility(models.Model):
	apartment = models.ForeignKey(Room, related_name='facility', on_delete=models.CASCADE)
	facilityTextbox = models.CharField(max_length=20, blank=False,verbose_name='Facility')
	image = models.ImageField(upload_to = "static/images/facilityLogo", default= "null" )
class Contact(models.Model):
	Name = models.CharField(max_length=20, blank=False)
	phoneNum = models.IntegerField()

class Testimonial(models.Model):
	Name = models.CharField(max_length=20, blank=False)
	role = models.CharField(max_length=20, blank=False)
	textBox = models.TextField(blank=False, verbose_name='Description')
	image = models.ImageField(upload_to = "static/images/testimonial" )

	def __str__(self):
		return self.Name

class Blog(models.Model):
	title = models.CharField(max_length=100, blank=False)
	writer = models.CharField(max_length=50, default='Anonymous')
	body = models.TextField()
	thumbnail = models.ImageField(upload_to = "static/images/blog")
	created_at = models.DateField(auto_now_add=True)

	def __str__(self):
		return self.title

pages/views.py
from django.shortcuts import render
from .models import *
# Create your views here.
def index(request):
	response = {}
	response['posts'] = Room.objects.all()
	response['testimonial'] = Testimonial.objects.all()
	return render(request, 'index.html', response)

def about(request):
	response = {}
	return render(request, 'about.html', response)

def katalog(request):
	response = {}
	response['apt'] = Apartment.objects.prefetch_related('room_set')
	return render(request, 'katalog.html', response)

def apartment(request,aptId):
	response= {}
	response['apt'] = Apartment.objects.prefetch_related('room_set').get(id=aptId)
	return render(request, 'apartment.html', response)

def room(request,roomId):
	response= {}
	response['room'] = Room.objects.get(id=roomId)
	response['room_lain'] = Room.objects.all()
	return render(request, 'room.html', response)


def blog(request):
	response = {}
	response['blog'] = Blog.objects.all()
	return render(request, 'blog.html', response)

pages/templates/blog.html
{% extends 'pages/layout/base.html' %}
{% load static %}
{% load staticfiles %}


{% block content %}
<section class="hero" id="hero">
       {% include "pages/partials/header.html" %}
       <div class="container">
            <div class="header-table">
                <div class="header-wrapper">
                </div> <!-- /.header-wrapper -->
            </div>
        </div> <!-- /.container -->
   </section>

    <section class="blog" id="blog">

        <div class="container">
            <h1 class=".whath1">Blog</h1>
            
    <div class="card-container" style="width:70%; height:300px;">
    <div style="height: 100%; width:auto;">
    <img src="https://images.wallpaperscraft.com/image/coffee_maker_coffee_dishes_110909_1280x720.jpg" alt="" style="width:400px; height:;">
    </div>

       <div class="card-txt">
       <p>{% lorem 1 b random %}</p>
       </div>
    </div>


<div class="card">
        <div class="row no-gutters">
            <div class="col-auto">
                <img src="//placehold.it/200" class="img-fluid" alt="">
            </div>
            <div class="col">
                <div class="card-block px-2">
                    <h4 class="card-title">Title</h4>
                    <p class="card-text">Description</p>
                    <a href="#" class="btn btn-primary">BUTTON</a>
                </div>
            </div>
        </div>
        <div class="card-footer w-100 text-muted">
            Footer stating cats are CUTE little animals
        </div>
    </div>
        </div>

    </section>




<style type="text/css">
.card-container {
    box-shadow : 0 4px 8px 0 rgba(0,0,0, 0.2);
    transition : 0.5s;
    border: 5px;
    width : 20%;
    display : flex;
    align: center;
}
.card-txt {
    display: inline-block;
}
a {
    
    text-decoration:none !important;
}
.whath2 {
    margin-top: 0;
    margin-bottom:2rem;
    font-family: Open Sans;
    font-style : normal;
    font-weight: bold;
    line-weight: normal;
    font-size : 2.5rem;
    color : #FAFAFA;
}
.wrapper {
   height:100%;
   width: 100%;
   margin: 0;
   padding: 0;
   border: 0;
}
.wrapper td {
   vertical-align: middle;
   text-align: center;
}

html,body
{
    overflow-x: hidden;
}

section {
    padding-right: 0;
    margin-right: 0;
    width:100vw;
}

    .hero
{
    background: url('/static/assets/hero.png');
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
    -o-background-size: cover;
    -moz-background-size: cover;
    -webkit-background-size: cover;
    background-attachment: fixed;
    -o-background-attachment: fixed;
    -moz-background-attachment: fixed;
    -webkit-background-attachment: fixed;
    height: 50vh;
    color: #FFF;


}
    .about
{
    background-color: #FFF;
    padding-bottom: 5%;

}
    .why
{
    background-color: #F3F3F3;

}
.header-wrapper {
    position: absolute;
left: 5%;
top: 40vh;
margin-right: 5%;
}
.header-title {
font-family: Open Sans;
font-style: normal;
font-weight: 800;
line-height: normal;
font-size: 4.5vw;
color: #FAFAFA;
}
.header-subtitle {
    position: absolute;
width: 257px;
height: 40px;
background: #F1F1F1;
opacity: 0.8;
border-radius: 60px;
}
.subtitle-wrapper {
    display: inline-block;
margin-top: 3%;
margin-left: 8%;
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 20px;
color: #121212;
}
.arrow {
    width: 7%;
}

.logo-left {
    max-width: 100%;
    height: auto;
    padding-left: 15%;
    padding-top: 15%;
    margin: auto;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}

.whath1{
    font-family: Open Sans;
font-style: normal;
font-weight: bold;
line-height: normal;
font-size: 4vw;

color: #121212;
}
.whatp {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: justify;
}
.whatwrapper {
    padding-top: 5%;
    padding-right: 5%;
}
.pWhy {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: center;
color: #121212;
}

.pTesti {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
text-align: justify;
font-size: 12pt;
color: #121212;
}

.sButton {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: center;
font-size: 2vh;
padding: 3% 3% 3% 3%;
color: #999999;
}

.sButton:hover {
    font-family: Roboto;
font-style: bold;
font-weight: bold;
line-height: normal;
font-size: 12pt;
text-align: center;
font-size: 2vh;
padding: 3% 3% 3% 3%;
}

.readmore{
width: 183px;
height: 28px;
background: #000;
border-radius: 60px;
margin-bottom: 5%;
}
.readmore-wrapper {
    display: inline-block;
margin-top: 3%;
margin-left: 10%;
text-align: center;
font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-decoration: none !important;
color: #FFF;
}
.hWhy {
    text-align: center;
    font-family: Open Sans;
    font-style: bold;
    font-weight: bold;
    line-height: normal;
    font-size: 3vw;
    color: #121212;
}
.card{
    /* Add shadows to create the "card" effect */
    box-shadow: 0px 2px 12px rgba(0, 0, 0, 0.2);
    transition: 0.3s;
    {% comment %} width: 30vw;
    min-height: 60vh; {% endcomment %}
    border-radius: 3%;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}
.crop {
    height: 50%;
    overflow: hidden;
}
/* Add some padding inside the card container */
.container {
    padding: 2px 16px;
    width: 100%;
}
.selengkapnyaWrapper {
    border-top: 2px solid #CCCCCC;
}
.selengkapnyaWrapper:hover {
    background: #F3F3F3;
    border-top: 2px solid #F3F3F3;
}
.slick-slide {
    margin-left: 0.5%;
    margin-right: 0.5%;
}
.roleText{
  font-family: Open Sans;
  font-style: normal;
  line-height: normal;
  font-weight: 600;
  font-size: 1.5vw;
color: #3C7BBE;
}
.footerLinks {
font-family: Roboto;
font-style: normal;
font-weight: 100;
color: #FAFAFA;
}


@media only screen and (max-width: 768px) {
    .header-title {
        font-size: 10vw;
    }
    .whath2 {
        display:none;
    }
.roleText {
  text-align: center;
}
.pTesti {
  text-align: center;
}
.whatwrapper {
    padding-left: 5%;
    padding-right: 5%;
    align-self: center;
}
.whath1{
    font-family: Open Sans;
    text-align: center;
    font-style: normal;
    font-weight: bold;
    line-height: normal;
    font-size: 8vw;

    color: #121212;
}
.logo-left {
    max-width: 100%;
    height: auto;
    margin: auto;
    padding-right: 15%;
}
.hWhy {
  text-align: center;
    font-family: Open Sans;
    font-style: bold;
    font-weight: normal;
    line-height: normal;
    font-size: 8vw;
    color: #121212;
}
.helper {
    display: inline-block;
    height: 100%;
}
</style>
{% endblock content %}

pages/templates/blog_detail.html
{% load static %}
{% load staticfiles %}
{% if detail %}
<p> {{detail}} </p>
{% endif %}

<script
  src="http://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<script src="{% static 'js/blog_detail.js' %}">
</script>

pages/templates/index.html

{% extends "pages/layout/base.html" %}
{% load staticfiles %}
{% load static %}
{% block content %}
   <section class="hero" id="hero">
       {% include "pages/partials/header.html" %}
       <div class="container">
            <div class="header-table">
                <div class="header-wrapper">
                        <h1 class="header-title" style="margin-bottom:0;"><strong>Cari Kamar di <span class="rotate">Taman Melati Margonda, Margonda Residence, Park View Apartment</span><strong></h1>
                    <h2 class="whath2">Depok based property and business consultant</h2>
                    <div class="header-subtitle">
                    <a href="{% url 'pages:katalog' %}" class="subtitle-wrapper" style="text-decoration:none; color:black;">
                        <p>Cari Kamar Sekarang    <img class="arrow" src="{% static 'assets/arrow.svg' %}"></p>
                    </a>
                </div> <!-- /.header-wrapper -->
            </div>
        </div> <!-- /.container -->
   </section>
   <section class="about">
    <div class="row">
         <div class="col-sm-3">
            <span class="helper"></span>
    <img class="logo-left" src="{% static 'assets/full_logo.svg' %}">
    </div>
    <div class="col-sm-9">
                    <span class="helper"></span>
        <div class="whatwrapper">
             <h1 class="whath1">What is Mahasewa</h1>
        <p class="whatp">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        <div class="readmore">
            <a href="{% url 'pages:about' %}" class="readmore-wrapper" style="color:white; text-decoration:none; margin-left:13%; margin-top:2%;">
                        <p>Baca Selengkapnya</p>
                    </a>
        </div>
        </div>
    </div>
    </div>
   </section>
   <section class="why" id="why">
       <div class="row">
           <div class="col-12" style="padding-top: 2.5%; padding-bottom: 5%;">
               <h1 class="whath1" style="text-align: center;">Why Mahasewa</h1>
           </div>
       </div>
       <div style="padding-left: 5%; padding-right: 5%" class="row">
       <div style="padding-bottom: 5%;" class="col-sm-4" >
        <table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/nyaman.svg' %}" alt="" /></td>
  </tr>
</table>
        <h2 class="hWhy">Nyaman</h2>
        <p class="pWhy">Keamanan bagi anda dalam bertransaksi dan hunian kami telah melalui seleksi </p>
           </div>
         <div style="padding-bottom: 5%;" class="col-sm-4">
<table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/terjangkau.svg' %}" alt="" /></td>
  </tr>
</table>                    <h2 class="hWhy">Terjangkau</h2>
        <p class="pWhy">Keamanan bagi anda dalam bertransaksi dan hunian kami telah melalui seleksi </p>
           </div>
         <div style="padding-bottom: 5%;" class="col-sm-4">
<table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/mentorship.svg' %}" alt="" /></td>
  </tr>
</table>                    <h2 class="hWhy">Mentorship</h2>
        <p class="pWhy">Keamanan bagi anda dalam bertransaksi dan hunian kami telah melalui seleksi </p>
           </div>
           </div>
   </section>
{% comment %} services {% endcomment %}
<section class="services" id="services">
    <div class="row">
           <div class="col-12" style="padding-top: 2.5%; padding-bottom: 5%;">
               <h1 class="whath1" style="text-align: center;">Services</h1>
           </div>
       </div>
       <div style="padding-left: 5%; padding-right: 5%" class="row">
       <div style="padding-bottom: 5%;" class="col-sm-4" >
        <table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/Circle.svg' %}" alt="" /></td>
  </tr>
</table>
        <h2 class="hWhy">Sewa kamar</h2>
           </div>
         <div style="padding-bottom: 5%;" class="col-sm-4">
<table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/Circle.svg' %}" alt="" /></td>
  </tr>
</table>                    
<h2 class="hWhy">Property Marketing</h2>
           </div>
         <div style="padding-bottom: 5%;" class="col-sm-4">
<table class="wrapper">
  <tr>
    <td><img src="{% static 'assets/Circle.svg' %}" alt="" /></td>
  </tr>
</table>                    
<h2 class="hWhy">Business Marketing</h2>
           </div>
           </div>
</section>


   <section id="listing" class="listing" style="background-color: #F3F3F3; padding-bottom:.6rem;">
        <div class="row" style="padding-left: 5%;">
           <div class="col-12" style="padding-top: 2.5%; padding-left: 5%;">
               <h1 class="whath1" style="text-align: left;">What We Offer</h1>
           </div>
                  </div>
           {% if posts %}
           <div style="padding-left: 5%; padding-right: 5%; padding-bottom: 1%;" class="slider">
                {% for i in posts %}
  <div class="card">
    <div class="crop">
          <img src="{{i.images.first.image.url}}" style="width:100%">
    </div>
  <div class="container" style="min-height: 32vh;">
    <h4 style="font-size: 4vh; text-align: center;" class="whath1"><b>{{ i.apartment.name }}  {{i.no}}</b></h4>
    <p style="font-size: 2vh;" class="pWhy">{{ i.descTextbox }}</p>
  </div>
  <a href="{% url 'pages:room' i.id %}" class="selengkapnyaWrapper">
          <p class="sButton">Baca Selengkapnya</p>
  </a>
</div>
                {% endfor %}
            </div>
            <div style="margin-left: 7%; margin-top: 1%;" class="readmore">
            <div class="readmore-wrapper" style="margin-left:13%;">
                        <a href="/katalog/" style="color:white;"><p style="left :10%;">Lihat semua kamar</p></a>
                    </div>
        </div>
                {% endif %}


   </section>
   <section id="testi" class="testi">
        <div class="row" style="padding-left: 5%;">
           <div class="col-12" style="padding-top: 2.5%; padding-left: 4%;">
               <h1 class="whath1" style="text-align: left;">What They Said</h1>
           </div>
                  </div>
           {% if testimonial %}
  <div style="margin-left: 5%; margin-right: 3%;" class="row">
                {% for i in testimonial %}
    <div style="margin-bottom: 3%;" class="col-sm-6">
           <div class="col-sm-6">
          <img src="{{i.image.url}}" style="width:100%">
    </div>
  <div class="col-sm-6">
    <h4 style="font-size: 4vh;" class="whath1"><b>{{ i.Name}}</h4>
      <h4 style="font-size:12pt;" class="roleText">{{ i.role}}</h4>

    <p style="font-size: 12pt" class="pTesti">{{ i.textBox }}</p>
  </div>
    </div>

                {% endfor %}
    </div>
                {% endif %}


   </section>
<style type="text/css">
a {
    
    text-decoration:none !important;
}
.whath2 {
    margin-top: 0;
    margin-bottom:2rem;
    font-family: Open Sans;
    font-style : normal;
    font-weight: bold;
    line-weight: normal;
    font-size : 2.5rem;
    color : #FAFAFA;
}
.wrapper {
   height:100%;
   width: 100%;
   margin: 0;
   padding: 0;
   border: 0;
}
.wrapper td {
   vertical-align: middle;
   text-align: center;
}

html,body
{
    overflow-x: hidden;
}

section {
    padding-right: 0;
    margin-right: 0;
    width:100vw;
}

    .hero
{
    background: url('{% static 'assets/hero.png' %}');
    background-repeat: no-repeat;
    background-position: center center;
    background-size: cover;
    -o-background-size: cover;
    -moz-background-size: cover;
    -webkit-background-size: cover;
    background-attachment: fixed;
    -o-background-attachment: fixed;
    -moz-background-attachment: fixed;
    -webkit-background-attachment: fixed;
    height: 100vh;
    color: #FFF;


}
    .about
{
    background-color: #FFF;
    padding-bottom: 5%;

}
    .why
{
    background-color: #F3F3F3;

}
.header-wrapper {
    position: absolute;
left: 5%;
top: 40vh;
margin-right: 5%;
}
.header-title {
font-family: Open Sans;
font-style: normal;
font-weight: 800;
line-height: normal;
font-size: 4.5vw;
color: #FAFAFA;
}
.header-subtitle {
    position: absolute;
width: 257px;
height: 40px;
background: #F1F1F1;
opacity: 0.8;
border-radius: 60px;
}
.subtitle-wrapper {
    display: inline-block;
margin-top: 3%;
margin-left: 8%;
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 20px;
color: #121212;
}
.arrow {
    width: 7%;
}

.logo-left {
    max-width: 100%;
    height: auto;
    padding-left: 15%;
    padding-top: 15%;
    margin: auto;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
}

.whath1{
    font-family: Open Sans;
font-style: normal;
font-weight: bold;
line-height: normal;
font-size: 4vw;

color: #121212;
}
.whatp {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: justify;
}
.whatwrapper {
    padding-top: 5%;
    padding-right: 5%;
}
.pWhy {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: center;
color: #121212;
}

.pTesti {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
text-align: justify;
font-size: 12pt;
color: #121212;
}

.sButton {
    font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-align: center;
font-size: 2vh;
padding: 3% 3% 3% 3%;
color: #999999;
}

.sButton:hover {
    font-family: Roboto;
font-style: bold;
font-weight: bold;
line-height: normal;
font-size: 12pt;
text-align: center;
font-size: 2vh;
padding: 3% 3% 3% 3%;
}

.readmore{
width: 183px;
height: 28px;
background: #000;
border-radius: 60px;
margin-bottom: 5%;
}
.readmore-wrapper {
    display: inline-block;
margin-top: 3%;
margin-left: 10%;
text-align: center;
font-family: Roboto;
font-style: normal;
font-weight: normal;
line-height: normal;
font-size: 12pt;
text-decoration: none !important;
color: #FFF;
}
.hWhy {
    text-align: center;
    font-family: Open Sans;
    font-style: bold;
    font-weight: bold;
    line-height: normal;
    font-size: 3vw;
    color: #121212;
}
.card{
    /* Add shadows to create the "card" effect */
    box-shadow: 0px 2px 12px rgba(0, 0, 0, 0.2);
    transition: 0.3s;
    width: 30vw;
    min-height: 60vh;
    border-radius: 3%;
}

/* On mouse-over, add a deeper shadow */
.card:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}
.crop {
    height: 50%;
    overflow: hidden;
}
/* Add some padding inside the card container */
.container {
    padding: 2px 16px;
    width: 100%;
}
.selengkapnyaWrapper {
    border-top: 2px solid #CCCCCC;
}
.selengkapnyaWrapper:hover {
    background: #F3F3F3;
    border-top: 2px solid #F3F3F3;
}
.slick-slide {
    margin-left: 0.5%;
    margin-right: 0.5%;
}
.roleText{
  font-family: Open Sans;
  font-style: normal;
  line-height: normal;
  font-weight: 600;
  font-size: 1.5vw;
color: #3C7BBE;
}
.footerLinks {
font-family: Roboto;
font-style: normal;
font-weight: 100;
color: #FAFAFA;
}
@media only screen and (max-width: 768px) {
    .header-title {
        font-size: 10vw;
    }
    .whath2 {
        display:none;
    }
.roleText {
  text-align: center;
}
.pTesti {
  text-align: center;
}
.whatwrapper {
    padding-left: 5%;
    padding-right: 5%;
    align-self: center;
}
.whath1{
    font-family: Open Sans;
    text-align: center;
    font-style: normal;
    font-weight: bold;
    line-height: normal;
    font-size: 8vw;

    color: #121212;
}
.logo-left {
    max-width: 100%;
    height: auto;
    margin: auto;
    padding-right: 15%;
}
.hWhy {
  text-align: center;
    font-family: Open Sans;
    font-style: bold;
    font-weight: normal;
    line-height: normal;
    font-size: 8vw;
    color: #121212;
}
.helper {
    display: inline-block;
    height: 100%;
}
</style>
<script>
     $(document).ready(function(){
      $('.slider').slick({
  speed: 300,
  slidesToShow: 3,
  slidesToScroll: 4,
  autoplay: true,
  autoplaySpeed: 3000,
  responsive: [
    {
      breakpoint: 1024,
      settings: {
        slidesToShow: 3,
        slidesToScroll: 3,
      }
    },
    {
      breakpoint: 600,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    },
    {
      breakpoint: 480,
      settings: {
        slidesToShow: 1,
        slidesToScroll: 1
      }
    }
    // You can unslick at a given breakpoint now by adding:
    // settings: "unslick"
    // instead of a settings object
  ]
      });
    });

    $(".rotate").textrotator({
  animation: "dissolve", // You can pick the way it animates when rotating through words. Options are dissolve (default), fade, flip, flipUp, flipCube, flipCubeUp and spin.
  separator: ",", // If you don't want commas to be the separator, you can define a new separator (|, &, * etc.) by yourself using this field.
  speed:4000 // How many milliseconds until the next word show.
});
</script>
{% endblock %}

pages/templates/pages/partials/header.html
{% load staticfiles %}
{% load static %}


<!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a href="{% url 'pages:index' %} " class="navbar-brand">
              <img class="logo" src="{% static 'assets/logonav.png' %}">
            </a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'pages:katalog' %}">Cari Kamar</a></li>
              <li><a href="{% url 'pages:about' %}">About Us</a></li>
              <li><a href="{% url 'pages:blog' %}">Blog</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

<style type="text/css">
  .navbar {
    position: absolute;
    width: 100vw;
  background: none;
  border: none;
  padding: 2.5% 5% 0% 5%;
}
.navbar-default .navbar-collapse, .navbar-default .navbar-form{
  border:none;
}
.navbar-brand {
  display:inline-block;
  float:left;
}

.nav.navbar-nav.navbar-right li a {
    font-family: Open Sans;
font-style: normal;
font-weight: bold;
line-height: normal;
font-size: 20px;

color: #F1F1F1;
}
@media only screen and (max-width: 400px) {
.logo {
  width: 50vw;
  height: auto;
}
}
</style>